Iter18
ShvetsovYura/metrics-collector pull request #18
Opened 2024-06-08 09:36 UTC by ShvetsovYura

добавлены примеры (_ example.go)  для хэндлеров
повторно отформатирован код

2024-06-11 23:39 UTC, Bazys requested changes
1. Очень мнгого неиспользуемых параметров
2. Очень много непроверячемых ошибок
подключи линтер errcheck

2024-06-11 23:39 UTC, Bazys commented on internal/server/options.go
>  type ServerOptions struct {
эта публичная структурка снаружи будет выглядеть как `server.ServerOptions`  - масло масляное.
https://go.dev/doc/effective_go#names
https://go.dev/blog/package-names

2024-06-11 23:39 UTC, Bazys commented on internal/storage/memory/memory.go
>  func (m *MemStorage) SetCounter(ctx context.Context, name string, val int64) error {
Параметр функции, названный `ctx`, не используется в теле функции. В Go, если определили параметр в функции, но не использовали его внутри, это считается неоптимальным стилем, поскольку параметр занимает место в сигнатуре функции и может сбивать с толку при чтении кода.
В данном случае, есть два возможных решения:
1. **Удаление параметра:** Если параметр `ctx` действительно не нужен для работы функции, его можно просто удалить из сигнатуры функции. Это делает код чище и проще для понимания.
2. **Переименование в `_`:** Если параметр не используется, но его наличие обязательно по какой-то причине (например, для соответствия интерфейсу или для использования в будущем), его можно переименовать в `_`. В Go, символ `_` используется для игнорирования переменной. Переменные, именованные как `_`, не обязаны быть использованы, т.е. не будет копирования неиспользуемого значения внутрь функции. Это позволяет сохранить сигнатуру функции неизменной, но явно указывает на то, что данный параметр в настоящее время не используется и избежать лишнего использования памяти.

2024-06-11 23:39 UTC, Bazys commented on internal/storage/memory/memory.go
> +		m.SetCounter(ctx, k, v)
а ошибку проверять?

2024-06-16 12:47 UTC, ShvetsovYura commented on internal/server/options.go
>  type ServerOptions struct {
Спасибо, исправил

2024-06-16 12:47 UTC, ShvetsovYura commented on internal/storage/memory/memory.go
> +		m.SetCounter(ctx, k, v)
Исправил

2024-06-16 12:54 UTC, ShvetsovYura commented
Спасибо большое за ревью!
Постарался исправить замечания
Прошу с пристрастием посмотреть!

2024-06-16 18:25 UTC, Bazys commented on internal/server/server.go
> +	logger.Log.Fatalf("не удалось запусить web сервер, %w", err)
%w нет смысла использовать с Fatalf - ты не оборачиваешь ошибку в этом случае

2024-06-16 18:25 UTC, Bazys commented on internal/storage/file/file.go
>  type FileStorage struct {
опять нейминг

2024-06-16 18:28 UTC, Bazys requested changes
есть несколько новых замечаний

2024-06-16 18:28 UTC, Bazys commented on internal/storage/memory/memory.go
>  	} else {
Использование `else` после `return` в блоке `if` избыточно. Потому что если условие в `if` истинно, функция завершится и вернёт значение на этом этапе, и выполнение кода дальше не пойдет. Это значит, что все, что находится в `else`, будет выполнено только если условие `if` не истинно, и нет нужды явно оборачивать этот код в `else`. Таким образом, код становится проще и уменьшается его вложенность, что облегчает его чтение и понимание. Поэтому вместо твоего варианта типа:
```go
if условие {
    return что-то
} else {
    // другой код
}
```
Можно написать кратко:
```go
if условие {
    return что-то
}
// другой код
```
Доп. ссылки:
1. [Effective Go](https://go.dev/doc/effective_go#if)
2. [Uber Go Style Guide](https://github.com/uber-go/guide/blob/master/style.md#reduce-nesting)
3. [Code Health: Reduce Nesting, Reduce Complexity ](https://testing.googleblog.com/2017/06/code-health-reduce-nesting-reduce.html)

2024-06-16 18:28 UTC, Bazys commented on internal/storage/memory/memory.go
> +func (m *MemStorage) SaveGaugesBatch(_ context.Context, gauges map[string]metric.Gauge) error {
`gauges` - ведь тоже неиспользуемый параметр

2024-06-16 18:28 UTC, Bazys commented on internal/storage/db/db.go
>  type DBStore struct {
опять нейминг

2024-06-17 17:05 UTC, ShvetsovYura commented
Большое спасибо за ревью! Это дает мне очень много знаний!
Сделал ренейминг файлов
Установил `golangci-lint` и прогнал код
Исправил замечания линтеров
Прогнал с флагом `--enable-all` и справил некоторые ошибки (все - пока вне моих возможностей =)
Подчерпнул из линтеров стилистические соглашения

[Uber Go Style Guide](https://github.com/uber-go/guide/blob/master/style.md#reduce-nesting) очень полезная для меня

2024-06-19 09:38 UTC, merged