Iter25
ShvetsovYura/metrics-collector pull request #22
Opened 2024-10-22 05:00 UTC by ShvetsovYura

2024-10-23 18:40 UTC, nburunova requested changes

2024-10-23 18:40 UTC, nburunova commented on cmd/agent/grpca.go
> +	r, err := c.GetMetric(ctx, &pb.GetMetricRequest{
что это за странный запрос?

2024-10-23 18:40 UTC, nburunova commented on cmd/agent/main.go
> +func main1() {
main1?

2024-10-23 18:40 UTC, nburunova commented on cmd/server/main.go
> +func ServerFactory(serverType string, hashKey string, trustedSubnet string) (server.IServer, error) {
функцию можно сделать приватной, то есть  с маленькой буквы назвать

2024-10-23 18:40 UTC, nburunova commented on cmd/agent/main.go
> +	client, err := selectSenderClient("grpc", opts.EndpointAddr, "", opts.Key, opts.CryptoKey)
предлагаю сделать флаг и env для определения режима запуска агента и сервера - http или grpc

2024-10-23 18:40 UTC, nburunova commented on internal/agent/grpc_client/client.go
> +	// var respHeaders metadata.MD
в ПР попал закоментированный код

2024-10-23 18:40 UTC, nburunova commented on internal/agent/grpc_client/client.go
> +func main() {
main?

2024-10-23 18:40 UTC, nburunova commented on internal/agent/grpc_client/client.go
> +	jsonData, _ := json.Marshal(req)
ошибку все же лучше обработать

2024-10-23 18:40 UTC, nburunova commented on internal/agent/grpc_client/client.go
> +	return err
вот тут точно нужно err , которая от маршала, вернуть? Или errInvoke? или nil?

2024-10-23 18:40 UTC, nburunova commented on internal/agent/grpc_client/interceptors/hash_interceptor.go
> +	outCtx := metadata.NewOutgoingContext(ctx, md)
хэш пустой?
тут точно нужно использовать NewOutgoingContext, а не AppendToOutgoingContext?

2024-10-23 18:40 UTC, nburunova commented on internal/agent/grpc_client/client.go
> +func encryptData(ctx context.Context, method string, req any, reply any, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
это интерсептор же? может его положить в папку с интерсепторами?

2024-10-23 18:40 UTC, nburunova commented on internal/agent/http_client/client.go
> +	headers.Add("X-Real-IP", addresses[0].String())
давай в grpc клиенте тоже добавлять X-Real-IP?

2024-10-24 14:41 UTC, ShvetsovYura commented on internal/agent/http_client/client.go
> +	headers.Add("X-Real-IP", addresses[0].String())
сделано

2024-10-24 14:58 UTC, ShvetsovYura commented on internal/agent/grpc_client/interceptors/hash_interceptor.go
> +	outCtx := metadata.NewOutgoingContext(ctx, md)
испраил

2024-10-24 15:00 UTC, ShvetsovYura commented on internal/agent/grpc_client/client.go
> +func main() {
косяк, торопился успеть ;)

2024-10-24 15:00 UTC, ShvetsovYura commented on internal/agent/grpc_client/client.go
> +	// var respHeaders metadata.MD
исправил

2024-10-24 15:00 UTC, ShvetsovYura commented on cmd/agent/main.go
> +	client, err := selectSenderClient("grpc", opts.EndpointAddr, "", opts.Key, opts.CryptoKey)
сделал, спасибо

2024-10-24 15:01 UTC, ShvetsovYura commented on cmd/server/main.go
> +func ServerFactory(serverType string, hashKey string, trustedSubnet string) (server.IServer, error) {
исправил

2024-10-24 15:02 UTC, ShvetsovYura commented on cmd/agent/main.go
> +func main1() {
исправил

2024-10-24 15:02 UTC, ShvetsovYura commented on cmd/agent/grpca.go
> +	r, err := c.GetMetric(ctx, &pb.GetMetricRequest{
дебажный код пробрался =)

2024-10-24 15:06 UTC, ShvetsovYura commented
Большое спасибо за ревью
Исправил замечания и дополнил код
Жду обратной связи

2024-10-24 17:20 UTC, nburunova requested changes

2024-10-24 17:20 UTC, nburunova commented on internal/agent/agent.go
> +			// a.mx.Lock()
в итоге без мьюекса делаем?

2024-10-24 17:22 UTC, ShvetsovYura commented on internal/agent/agent.go
> +			// a.mx.Lock()
Я проверю сейчас. С ним что-то зависало жёстко ;)

2024-10-24 17:49 UTC, ShvetsovYura commented
Очень хорошо, что обратила внимание на mutex. Включил
Проблема с зависаниями была не в нем, а в другом месте (уже починил)
Спасибо!

2024-10-25 09:27 UTC, nburunova approved these changes

2024-10-26 11:22 UTC, merged